baseURL = "https://aemukit.github.io/"
theme = "hugo-bearblog"
title = "aemukit"
author = "aemukit"
languageCode = "en-US"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/blog/:slug/"

[params]
  showAllPostsOnHomePage = true
  description = "My personal blog"
